### ISSUE TITLE
Object reference not set to an instances object

### ISSUE THREAD

**Issue by alexandernesbitt** [teocomi/Reveche#1]
Hi,

When trying to check a Revit 2015 file, it throws up the following error:

"exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Reveche.MainWindow.GetRawBasicFileInfo(String revitFileName)"

If I click 'OK', I get:

"Array cannot be null.
Parameter name: bytes"

If I click 'OK', I get:

All information about the file excluding the additional info (which I assume this is normal) and the version.

Any ideas what that means or how to fix?

Thanks,
Alex

**Comment by teocomi** [comment]
Hi Alex,
I cannot replicate the bug, can you please verify if:
- it happens for every Revit 2015 file
- it happens also with other Revit file versions ([here a 2016 rvt](https://drive.google.com/open?id=0B5QYNPApCsQENnpFR1MwazN0MWs))
- it happens in other machines as well

If it happens only with a specific file and you can send it over I'll have a look.

Thanks

**Comment by teocomi** [comment]
Will close this issue as no additional info was given.
