### ISSUE TITLE
Revit 2019 files showing as version 'k' and not '2019'

### ISSUE THREAD

**Issue by jsdbroughton** [teocomi/Reveche#3]
![2019k](https://user-images.githubusercontent.com/760691/51400056-52598980-1b3f-11e9-9f50-3bfdc7fb16ec.PNG)

**Comment by teocomi** [comment]
Ugh, thanks, unfortunately 2019 files have a different format which might not make parsing possible... Will investigate...

**Comment by jsdbroughton** [comment]
Like me to take a look and PR instead?

**Comment by teocomi** [comment]
Of course, feel free!
